[project]
title = "Big Three Anime"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "Script"

[branding]
name = "Preswald Project"
logo = "images/BigThree logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.BigThree]
type = "csv"
path = "data/BigThree.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 